version: '3.3'

networks:
  todolist:
    external: false

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - todolist
#  user_groups_api:
#    build:
#      context: api
#      dockerfile: Dockerfile
#    networks:
#      - todolist

# Names our volume
volumes:
  mysql_db: